import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  image: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'Roboto',
    backgroundColor: '#F5F5F5',
    fontColor: 'black',
  },
  Header: {
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 34,
    fontWeight: 'bold',
    fontColor: 'black',
    fontFamily: 'Roboto',
  },
  InputText: {
    borderColor: '#739072',
    borderWidth: 2,
    borderRadius: 50,
    width: '90%',
    padding: 10,
    paddingStart: 30,
    margin: 10,
    fontFamily: 'Roboto',
  },
  btn: {
    width: '80%',
    padding: 10,
    margin: 10,
    borderRadius: 50,
    height: 50,
    backgroundColor: '#3A4D39',
    fontFamily: 'Roboto',
  },
  appButtonContainer: {
    elevation: 8,
    backgroundColor: '#4F6F52',
    borderRadius: 50,
    paddingVertical: 12,
    paddingHorizontal: 12,
    width: '90%',
    height: 50,
    margin: 10,
    fontFamily: 'Roboto',
  },
  appButtonText: {
    fontSize: 15,
    color: '#fff',
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  SingInText: {
    fontSize: 15,
    color: '#739072',
    fontWeight: 'bold',
    alignSelf: 'center',
    fontFamily: 'Roboto',
  },
  LinkInputText: {
    fontSize: 15,
    color: '#739072',
    fontWeight: 'bold',
    alignSelf: 'center',
    borderRadius: 50,
    width: '90%',
    paddingStart: 30,
    margin: 10,
    borderWidth: 2,
    height: 50,
    fontFamily: 'Roboto',
  },
  Links: {
    flex: 1,
    fontSize: 15,
    color: '#739072',
    fontWeight: 'bold',
    alignSelf: 'center',
    paddingRight: 10,
    fontFamily: 'Roboto',
  },
  appButtonContainerLinks: {
    elevation: 8,
    backgroundColor: '#4F6F52',
    borderRadius: 50,
    paddingVertical: 12,
    paddingHorizontal: 12,
    width: '90%',
    height: 50,
    paddingStart: 40,
    margin: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    fontFamily: 'Roboto',
  },

  LinksContainer: {
    flex: 2,
    marginTop: 20,
  },
  linksHeader: {
    padding: 10,
    paddingBottom: 20,
    justifyContent: 'center',
    marginTop: 100,
    fontSize: 15,
    color: '#739072',
    alignSelf: 'center',
    fontWeight: 'bold',
    fontFamily: 'Roboto',
  },
  srolview: {
    flex: 1,
    height: '100%',
    width: '100%',
    backgroundColor: '#F5F5F5',
    fontFamily: 'Roboto',
  },

  DashboardBlocks: {
    alignItems: 'center',
    margin: 10,
    paddingStart: 10,
    padding: 10,
    borderRadius: 20,
    backgroundColor: '#4F6F52',
    width: '90%',
    height: '25%',
    fontFamily: 'Roboto',
  },

  codechefbackground: {
    backgroundColor: '#E1C78F',
    flex: 1,
  },
  userNameBox: {
    alignItems: 'center',
    borderBottomEndRadius: 30,
    borderBottomStartRadius: 30,
    backgroundColor: '#B0926A',
    width: '100%',
    height: '20%',
    color: '#ffffff',
    fontFamily: 'Roboto',
  },
  codechefframe: {
    alignItems: 'center',
    margin: 10,
    flex: 1,
    paddingStart: 10,
    padding: 10,
    borderRadius: 20,
    backgroundColor: '#000000',
    width: '90%',
    height: '50%',
    fontFamily: 'Roboto',
  },
  username: {
    color: '#ffffff',
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    fontSize: 30,
    marginTop: 30,
    alignSelf: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  ranking: {
    color: '#ffffff',
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    fontSize: 20,
    marginTop: 10,
    alignSelf: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  listofPractice: {
    flex: 1,
    fontWeight: 'bold',
    fontSize: 20,
    backgroundColor: '#FAE7C9',
    borderRadius: 10,
    padding: 10,
    marginTop: 10,
    width: '95%',
    alignSelf: 'center',
    alignContent: 'center',
  },
  listofText: {
    fontWeight: 'bold',
    fontSize: 15,
    padding: 14,
    color: '#000000',
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
  tittle: {
    fontWeight: 'bold',
    fontSize: 30,
    padding: 10,
    color: '#000000',
    alignSelf: 'center',
    alignItems: 'center',
    alignContent: 'center',
    justifyContent: 'center',
  },
});

const st = StyleSheet.create({
  container: {
    backgroundColor: '#ECE3CE',
    flex: 1,
    marginBottom: 5,
  },
  content: {
    flex: 1,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#ffff',
    marginTop: 10,
    marginBottom: 5,
    width: '95%',
    height: 300,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.9,
    shadowRadius: 5,
    fontFamily: 'Roboto',
  },
  image: {
    width: 200,
    height: 200,
  },
  heading: {
    fontSize: 30,
    fontWeight: 'bold',
    color: '#000',
    paddingTop: 10,
    fontFamily: 'Roboto',
  },
});
export default styles;
